// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf6sqSbpk6B9y5rSoRxBa-whCxoV4j8vE',
    appId: '1:729590756186:ios:5d54a6eb9fda4a1dac3963',
    messagingSenderId: '729590756186',
    projectId: 'mye-connect',
    storageBucket: 'mye-connect.appspot.com',
    iosClientId:
        '729590756186-bv966akb3up841vcfk5sf64209j9k5r5.apps.googleusercontent.com',
    iosBundleId: 'fr.connect.my-econnect',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsldnGYnnPV38DnagK0lE5sIDfwFhl5Io',
    appId: '1:729590756186:android:0be725db2c945338ac3963',
    messagingSenderId: '729590756186',
    projectId: 'mye-connect',
    storageBucket: 'mye-connect.appspot.com',
  );
}
